/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mushrooms;

/**
 *
 * @author erb39405
 */
public class mushroomJFrame extends javax.swing.JFrame {

    /**
     * Creates new form mushroomJFrame
     */
    public mushroomJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        odor = new javax.swing.JLabel();
        fishyRadioButton = new javax.swing.JRadioButton();
        pungentRadioButton = new javax.swing.JRadioButton();
        creosoteRadioButton = new javax.swing.JRadioButton();
        gillSize = new javax.swing.JLabel();
        narrowRadioButton = new javax.swing.JRadioButton();
        gillColor = new javax.swing.JLabel();
        buffRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 51), new java.awt.Color(0, 204, 51)));

        header.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        header.setForeground(new java.awt.Color(0, 153, 51));
        header.setText("Welcome to the Mushroom Database");

        odor.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        odor.setText("Odor: ");

        fishyRadioButton.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        fishyRadioButton.setText("Fishy (f)");
        fishyRadioButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        pungentRadioButton.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        pungentRadioButton.setText("Pungent (p)");
        pungentRadioButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));
        pungentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pungentRadioButtonActionPerformed(evt);
            }
        });

        creosoteRadioButton.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        creosoteRadioButton.setText("Creosote (c)");
        creosoteRadioButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 1, true));

        gillSize.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        gillSize.setText("Gill Size: ");

        narrowRadioButton.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        narrowRadioButton.setText("Narrow (n)");

        gillColor.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        gillColor.setText("Gill Color: ");

        buffRadioButton.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        buffRadioButton.setText("Buff (b)");
        buffRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buffRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(header)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(odor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pungentRadioButton)
                            .addComponent(creosoteRadioButton)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(fishyRadioButton)
                                .addGap(38, 38, 38)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(gillColor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buffRadioButton))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(gillSize)
                                .addGap(18, 18, 18)
                                .addComponent(narrowRadioButton)))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(header)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(odor))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(fishyRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pungentRadioButton)
                        .addGap(6, 6, 6)
                        .addComponent(creosoteRadioButton))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gillSize)
                            .addComponent(narrowRadioButton))
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gillColor)
                            .addComponent(buffRadioButton))))
                .addContainerGap(438, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buffRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buffRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buffRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mushroomJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mushroomJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mushroomJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mushroomJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mushroomJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton buffRadioButton;
    private javax.swing.JRadioButton creosoteRadioButton;
    private javax.swing.JRadioButton fishyRadioButton;
    private javax.swing.JLabel gillColor;
    private javax.swing.JLabel gillSize;
    private javax.swing.JLabel header;
    private javax.swing.JRadioButton narrowRadioButton;
    private javax.swing.JLabel odor;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton pungentRadioButton;
    // End of variables declaration//GEN-END:variables
}
